### ISSUE TITLE
Tracking: Static JNI

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#1008]
### Issue description

Tracking ticket for codebase-wide Static JNI support.
```[tasklist]
### Static JNI
- [ ] https://github.com/elide-dev/elide/pull/1007
- [ ] https://github.com/elide-dev/elide/pull/1006
- [ ] https://github.com/elide-dev/elide/pull/950
- [ ] https://github.com/elide-dev/elide/issues/992
- [ ] https://github.com/elide-dev/elide/pull/1018
- [ ] #1019
- [ ] #1022
- [x] Audit of all native libraries in use
```

**Comment by sgammon** [comment]
this is done for now :)
