### ISSUE TITLE
Tracking: Alpha 10

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#1036]
### Issue description

Pre-flight checklist for the next release, at `1.0.0-alpha10`.
```[tasklist]
### Alpha 10
- [x] Transport benchmarks/fixes
- [x] Smoke tests on each OS/arch
- [ ] Release notes: Thank EJ Technologies
```

```[tasklist]
### Changelog
- [ ] https://github.com/elide-dev/elide/pull/1044
- [ ] #1034
- [ ] #1026
- [ ] #1022
- [ ] #1019
- [ ] #1018
- [ ] #1017
- [ ] #1010
- [ ] #1007
- [ ] #1006
- [ ] #995
- [ ] #993
- [ ] #991
- [ ] #985
- [ ] #983
- [ ] #982
- [ ] #981
- [ ] #977
- [ ] #969
- [ ] #1030
- [ ] #956
- [ ] #955
- [ ] #950
- [ ] #939
- [ ] #925
- [ ] #922
- [ ] #914
- [ ] #913
```

```[tasklist]
### Issue Updates
- [ ] #1024
- [ ] #994
- [ ] #992
- [ ] #990
- [ ] #989
- [ ] #984
- [ ] #910
- [ ] #906
- [ ] #824
- [ ] #883
- [ ] #882
- [ ] #911
```
