### ISSUE TITLE
Tracking: Alpha 4 Release

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#32]
Tracking ticket for follow-up to the initial release.

- [x] Early major functionality, pt 2
  - [x] #12
  - [x] #89
- [x] Basic stuff
  - [x] Presets for Micronaut config
  - [x] Error handlers
- [x] Dev Experience
  - [x] Published narrative docs
  - [x] Small website
  - [x] Benchmarks (continuous)
