### ISSUE TITLE
Tracking: Alpha Launch

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#398]
This issue tracks features and bugs which need to land before the official Alpha launch of Elide:

```[tasklist]
### Alpha Launch
- [ ] https://github.com/elide-dev/elide/issues/402
- [ ] #397
- [ ] #396
- [ ] https://github.com/elide-dev/elide/issues/123
- [ ] https://github.com/elide-dev/elide/issues/210
- [ ] https://github.com/elide-dev/elide/issues/367
- [ ] https://github.com/elide-dev/elide/issues/226
- [ ] https://github.com/elide-dev/elide/issues/134
- [ ] https://github.com/elide-dev/elide/issues/386
- [ ] https://github.com/elide-dev/elide/issues/366
- [ ] https://github.com/elide-dev/elide/issues/399
- [ ] #394
- [ ] #225
- [ ] https://github.com/elide-dev/elide/issues/178
- [ ] https://github.com/elide-dev/elide/issues/165
- [ ] https://github.com/elide-dev/elide/issues/153
- [ ] https://github.com/elide-dev/elide/issues/99
- [ ] https://github.com/elide-dev/elide/issues/70
```

```[tasklist]
### Alpha Launch PRs
- [ ] https://github.com/elide-dev/elide/pull/400
- [ ] https://github.com/elide-dev/elide/pull/395
- [ ] https://github.com/elide-dev/elide/pull/393
- [ ] https://github.com/elide-dev/elide/pull/383
- [ ] https://github.com/elide-dev/elide/pull/382
- [ ] https://github.com/elide-dev/elide/pull/350
- [ ] https://github.com/elide-dev/elide/pull/344
- [ ] https://github.com/elide-dev/elide/pull/343
- [ ] https://github.com/elide-dev/elide/pull/341
- [ ] https://github.com/elide-dev/elide/pull/325
- [ ] https://github.com/elide-dev/elide/pull/320
- [ ] https://github.com/elide-dev/elide/pull/319
- [ ] https://github.com/elide-dev/elide/pull/318
- [ ] https://github.com/elide-dev/elide/pull/314
```

```[tasklist]
### Dependency Upgrades
- [x] **GraalVM `23.1.x` (Upon release)**
- [x] GraalVM `dev`
- [x] ~~GraalVM `20.0.2` / `23.0.1`~~
- [x] ~~GraalVM `17.0.8` / `23.0.1`~~
- [x] **Java 21**
- [x] Java 20
- [x] ~~Java 17~~
- [x] **Kotlin → `1.9.20-Beta`**
- [x] ~~Kotlin → `1.9.10`~~
- [x] ~~Kotlin → `1.9.0`~~
- [x] **Micronaut → `4.1.0`**
- [x] ~~Micronaut → `4.0.0`~~
```
