### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#462]
### Issue description

Bugs discovered after the Alpha launch version, `1.0.0-alpha7`.
```[tasklist]
### Known Issues
- [ ] https://github.com/elide-dev/elide/issues/459
- [ ] https://github.com/elide-dev/elide/issues/461
- [ ] https://github.com/elide-dev/elide/issues/456
- [ ] https://github.com/elide-dev/elide/issues/458
- [ ] https://github.com/elide-dev/elide/issues/469
- [ ] https://github.com/elide-dev/elide/issues/463
- [ ] https://github.com/elide-dev/elide/issues/480
- [ ] https://github.com/elide-dev/elide/issues/789
- [ ] https://github.com/elide-dev/elide/issues/790
```
