### ISSUE TITLE
Release blockers for alpha9

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#905]
Issues reported from testing

- Won't run on macOS AMD64 (see attached)
- Won't run on Windows (Ruby crash)

![image](https://github.com/elide-dev/elide/assets/171897/f3fc9b27-0414-41e2-98d3-7c78d0636bbd)
```[tasklist]
### Tasks
- [ ] https://github.com/elide-dev/elide/issues/906
- [x] Won't run on AMD64 macOS
- [x] Won't run on Windows (Ruby crashes)
```
