### ISSUE TITLE
Static JNI for JNA

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#992]
### Issue description

It would be cool to embed the JNA native pieces so we don't have to load them on-demand at runtime.
```[tasklist]
### Tasks
- [ ] elide-dev/jna#1
- [ ] https://github.com/elide-dev/elide/pull/991
- [ ] https://github.com/elide-dev/elide/pull/988
- [ ] https://github.com/elide-dev/elide/issues/990
- [ ] https://github.com/elide-dev/elide/issues/984
```
